version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animations-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - animations_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: animations-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - animations_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: animations-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - animations_network

  node:
    image: node:20
    container_name: animations-node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - animations_network

networks:
  animations_network:
    driver: bridge

volumes:
  dbdata:
