services:
  - type: web
    name: animations
    env: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm ci
      npm run build
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: animations
          type: web
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: ASSET_URL
        fromService:
          name: animations
          type: web
          property: host
      - key: VITE_APP_URL
        fromService:
          name: animations
          type: web
          property: host
